# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                deno: ["v1.12.0"]

        steps:
            - name: Setup
              uses: actions/checkout@v2
            - name: Install Deno
              uses: denolib/setup-deno@v2.3.0
              with:
                  deno-version: ${{ matrix.deno }}
            - name: Upgrade Node
              run: sudo npm install --global n && sudo n latest
            - name: Download remote cache
              run: curl -O https://dl.dropboxusercontent.com/s/gtjdehk8eqoqtl3/.cache.zip && unzip -oq .cache.zip
            - name: Cache dependencies
              run: DENO_DIR=.cache deno run --unstable --allow-all --import-map import-map.json cli/cli.ts cache
            - name: Test server
              run: DENO_DIR=.cache deno run --unstable --allow-all --import-map import-map.json cli/cli.ts test
